/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tamagotchi;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Tio Ranchero
 */
public class Creacion extends javax.swing.JFrame {
    int tamagotchiSeleccionado = 0;
    String[] array_mascotas = {"Cuadrado", "Circulo", "Triangulo"};
    String ruta = "C:\\Program Files (x86)\\save_file.txt";
//    String tipo = "";
//    String status = "";
    
    public Creacion() {
        setTitle("Tamagotchi Creator v2.000.2 Nintendo All Rights Reserved 2017");
        setSize(250,250);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        
        initComponents();
        jPanel1.getRootPane().setDefaultButton(bt_Crear);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_grupoMascota = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lb_seleccion = new javax.swing.JLabel();
        lb_nombreDelTamagotchi = new javax.swing.JLabel();
        tf_Circulo = new javax.swing.JLabel();
        tf_Cuadrado = new javax.swing.JLabel();
        tf_Triangulo = new javax.swing.JLabel();
        bt_Cuadrado = new javax.swing.JRadioButton();
        bt_Circulo = new javax.swing.JRadioButton();
        bt_Triangulo = new javax.swing.JRadioButton();
        bt_Crear = new javax.swing.JButton();
        bt_Regresar = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        lb_fondo = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lb_seleccion.setFont(new java.awt.Font("Californian FB", 0, 36)); // NOI18N
        lb_seleccion.setText("Selecciona una mascota a crear");
        jPanel1.add(lb_seleccion);
        lb_seleccion.setBounds(120, 50, 610, 90);

        lb_nombreDelTamagotchi.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lb_nombreDelTamagotchi.setText("Nombre del Tamagotchi");
        jPanel1.add(lb_nombreDelTamagotchi);
        lb_nombreDelTamagotchi.setBounds(10, 490, 200, 40);

        tf_Circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tamagotchi/imagenes/Nueva carpeta/TrianguloGigante.png"))); // NOI18N
        tf_Circulo.setText("jLabel2");
        jPanel1.add(tf_Circulo);
        tf_Circulo.setBounds(480, 150, 190, 220);

        tf_Cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tamagotchi/imagenes/Nueva carpeta/CuadradoGigante.png"))); // NOI18N
        tf_Cuadrado.setText("jLabel1");
        jPanel1.add(tf_Cuadrado);
        tf_Cuadrado.setBounds(0, 150, 180, 220);

        tf_Triangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tamagotchi/imagenes/Nueva carpeta/CirculoGigante.png"))); // NOI18N
        tf_Triangulo.setText("jLabel1");
        jPanel1.add(tf_Triangulo);
        tf_Triangulo.setBounds(260, 150, 190, 220);

        bt_grupoMascota.add(bt_Cuadrado);
        bt_Cuadrado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_Cuadrado.setText("Cuadrado");
        bt_Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CuadradoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Cuadrado);
        bt_Cuadrado.setBounds(40, 390, 100, 40);

        bt_grupoMascota.add(bt_Circulo);
        bt_Circulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_Circulo.setText("Circulo");
        bt_Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CirculoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Circulo);
        bt_Circulo.setBounds(300, 390, 100, 40);

        bt_grupoMascota.add(bt_Triangulo);
        bt_Triangulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt_Triangulo.setText("Triangulo");
        bt_Triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TrianguloActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Triangulo);
        bt_Triangulo.setBounds(530, 390, 100, 40);

        bt_Crear.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bt_Crear.setText("Crear!!");
        bt_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Crear);
        bt_Crear.setBounds(460, 490, 190, 40);

        bt_Regresar.setBackground(new java.awt.Color(255, 255, 255));
        bt_Regresar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bt_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tamagotchi/imagenes/Nueva carpeta/wwwewee.png"))); // NOI18N
        bt_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Regresar);
        bt_Regresar.setBounds(20, 10, 60, 40);

        tf_nombre.setToolTipText("");
        jPanel1.add(tf_nombre);
        tf_nombre.setBounds(210, 490, 240, 40);

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tamagotchi/imagenes/Nueva carpeta/VW2DYbL.png"))); // NOI18N
        lb_fondo.setText("jLabel6");
        jPanel1.add(lb_fondo);
        lb_fondo.setBounds(0, -430, 900, 1050);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RegresarActionPerformed
        this.dispose();
        Seleccion nuevoFrame = new Seleccion();
        nuevoFrame.setLocation(this.getLocation());
        nuevoFrame.setVisible(true);
    }//GEN-LAST:event_bt_RegresarActionPerformed

    private void bt_CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CuadradoActionPerformed
        seleccionarMascota(0);
    }//GEN-LAST:event_bt_CuadradoActionPerformed

    private void bt_CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CirculoActionPerformed
        seleccionarMascota(1);        
    }//GEN-LAST:event_bt_CirculoActionPerformed

    private void bt_TrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TrianguloActionPerformed
        seleccionarMascota(2);
    }//GEN-LAST:event_bt_TrianguloActionPerformed

    private void bt_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearActionPerformed
        if( (!"".equals(tf_nombre.getText())) && (tamagotchiSeleccionado != 0)){
            String linea_txt = "";
            String arrayLineas[] = new String [5];
            int indiceLineas = 0;

            try {
                // Lectura de Tamagotchis guardados
                BufferedReader lector = new BufferedReader(new FileReader(ruta));
                while((linea_txt = lector.readLine()) != null){
                    arrayLineas[indiceLineas] = linea_txt;
                    indiceLineas++;
                }
                lector.close();
                // Escritura de nuevo Tamagotchi
                BufferedWriter escritor = new BufferedWriter(new FileWriter(ruta));
                for (int i = 0; i < arrayLineas.length; i++) {
                    if( arrayLineas[i] != null ){
                        escritor.write(arrayLineas[i]);
                        escritor.newLine();
                    }
                }
                escritor.write(array_mascotas[tamagotchiSeleccionado - 1] + "," + tf_nombre.getText()+ "," + "Normal" +"," +"100" +"," +"0" +"," +"0" +","+"0\n");
                escritor.close();
                this.dispose();
                Seleccion nuevoFrame = new Seleccion();
                nuevoFrame.setLocation(this.getLocation());
                nuevoFrame.setVisible(true);
            } catch ( IOException exception ) {
                JOptionPane.showMessageDialog(null,"No se pudo crear el Tamagotchi"  , "Ups, ha ocurrido un error" , JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Necesitas seleccionar un tipo y elegir un nombre", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_CrearActionPerformed

    public void seleccionarMascota(int indice){
        for (int i = 0; i < array_mascotas.length; i++) {
            if(i == indice){
                tamagotchiSeleccionado = indice + 1;
                bt_Crear.setVisible(true);
                tf_nombre.setVisible(true);
                
            }
        }        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bt_Circulo;
    private javax.swing.JButton bt_Crear;
    private javax.swing.JRadioButton bt_Cuadrado;
    private javax.swing.JButton bt_Regresar;
    private javax.swing.JRadioButton bt_Triangulo;
    private javax.swing.ButtonGroup bt_grupoMascota;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JLabel lb_nombreDelTamagotchi;
    private javax.swing.JLabel lb_seleccion;
    private javax.swing.JLabel tf_Circulo;
    private javax.swing.JLabel tf_Cuadrado;
    private javax.swing.JLabel tf_Triangulo;
    private javax.swing.JTextField tf_nombre;
    // End of variables declaration//GEN-END:variables

}
