/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tamagotchi;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Tio Ranchero
 */
public class Login extends javax.swing.JFrame {

    ;
     
    public Login() {
    setTitle("Porfavor Ingresa tus datos");
    setLocationRelativeTo(null);
    setVisible(true);
  
        initComponents();
        jPanel1.getRootPane().setDefaultButton(bt_entrar);
        tf_usuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_usuario = new javax.swing.JTextField();
        lb_usuario = new javax.swing.JLabel();
        lb_contraseña = new javax.swing.JLabel();
        tf_contrasena = new javax.swing.JPasswordField();
        bt_entrar = new javax.swing.JButton();
        lb_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(null);
        jPanel1.add(tf_usuario);
        tf_usuario.setBounds(310, 200, 177, 29);

        lb_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_usuario.setText("Usuario");
        jPanel1.add(lb_usuario);
        lb_usuario.setBounds(200, 200, 110, 30);

        lb_contraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_contraseña.setText("Contraseña");
        jPanel1.add(lb_contraseña);
        lb_contraseña.setBounds(200, 290, 110, 30);
        jPanel1.add(tf_contrasena);
        tf_contrasena.setBounds(310, 290, 177, 29);

        bt_entrar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_entrar);
        bt_entrar.setBounds(240, 430, 190, 40);

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tamagotchi/imagenes/Nueva carpeta/8-bit-purple-sunset-40894-1920x1080.jpg"))); // NOI18N
        lb_background.setText("jLabel1");
        jPanel1.add(lb_background);
        lb_background.setBounds(-10, -310, 700, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
      String pass;
      String user;
     
      user = tf_usuario.getText();
      pass = tf_contrasena.getText();

     if(pass.equals("12345") && user.equals("daniel") ){
     JOptionPane.showMessageDialog(null, "Bienvenido usuario :" + " daniel" , "Contraseña aceptada", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        Seleccion nuevoFrame = new Seleccion();
        nuevoFrame.setLocation(this.getLocation());
        nuevoFrame.setVisible(true);
      }
     
     else{
     JOptionPane.showMessageDialog(null, "Contraseña equivocada, porfavor intente otra vez" , "Contraseña equivocada", JOptionPane.INFORMATION_MESSAGE);
     } 
    }//GEN-LAST:event_bt_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_background;
    private javax.swing.JLabel lb_contraseña;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPasswordField tf_contrasena;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
